version: "3.9"

services:
    server:
        container_name: server
        build:
            context: ./
            dockerfile: Dockerfile.dev
        ports:
            - "5000:5000"
        environment:
            DATABASE_URL: postgres://postgres:postgres@postgres:5432/dev
        volumes:
            - ./:/app

        restart: "unless-stopped"
        networks:
            - backend
        # links:
        #     - postgres
        # depends_on:
        #     - postgres

    # postgres:
    #     image: postgres:15.3-alpine3.18
    #     restart: always
    #     environment:
    #         - POSTGRES_USER=admin
    #         - POSTGRES_PASSWORD=postgres
    #         - POSTGRES_DB=dev
    #     ports:
    #         - "5200:5432"
    #     volumes:
    #         - data:/var/lib/postgresql/data
    #     networks:
    #         - backend

networks:
    backend:
        driver: bridge

volumes:
    data:
        driver: local
